name: Test Management
run-name: ${{ github.actor }} is running application tests
on: ["push"]
jobs:
  Install-Packages:
    runs-on: node:18.14.0-alpine
    steps:
      - name: ğŸ‰ Installing needed packages
      - run: npm --global add pnpm
      - run: pnpm install
  Unitary-Testing:
    runs-on: node:18.14.0-alpine
    steps:
      - name: ğŸ§ Running unitary tests
      - run: pnpm run test:unit
